const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { test } = require('node:test')
const { harness, measure } = require('./support/d1-workload.cjs')
const root = path.resolve(__dirname, '..')
const digest = async bytes => Buffer.from(await crypto.subtle.digest('SHA-256', bytes)).toString('hex')
async function realtime(h, sql, values = []) {
  const ns=await h.mf.getDurableObjectNamespace('SEROTINE_REALTIME')
  const response=await ns.get(ns.idFromName('relay-realtime-v1')).fetch('https://realtime.internal/query', {method:'POST',body:JSON.stringify([{sql,values}])})
  assert.equal(response.status,200)
  return (await response.json())[0]
}

test('representative workloads keep the 90% D1 reduction and zero idle/call write budgets', {timeout:180_000}, async()=>{
  const baseline=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/d1-baseline.json'),'utf8'))
  const after=await measure(root,true)
  for(const [name,prior] of Object.entries(baseline.scenarios)){
    const current=after.scenarios[name]
    assert.ok(current.rowsWritten<=prior.rowsWritten*0.1,`${name}: ${prior.rowsWritten} -> ${current.rowsWritten}`)
    if(['idle-10m','call-10m','room-10m'].includes(name))assert.equal(current.rowsWritten,0,name)
    assert.ok(Object.keys(current.bySql).every(sql=>!/(RequestNonce|CallPresence|CallSession|CallSignal|CallRoom|RelaySignal)/.test(sql)),name)
  }
})

test('real R2 payloads preserve encryption, deduplication, linked-device history and fail without cursor advancement', async t=>{
  const h=await harness(root,true);t.after(()=>h.dispose())
  const a=await h.identity(),b=await h.identity(),outsider=await h.identity()
  const plaintext='legacy embedded attachment: '+Buffer.from('file bytes').toString('base64')
  const encryptedData=await h.client.encryptForPeer(plaintext,a.pair.privateKey,b.publicKey)
  const data={id:crypto.randomUUID(),recipientPubKey:b.publicKey,encryptedData}
  await h.request(a,'event:send',data)
  const d1=await h.mf.getD1Database('serotine_db')
  const stored=await d1.prepare('SELECT * FROM RelayEvent').first()
  assert.ok(stored.encryptedData.startsWith('@r2:v2:'))
  assert.equal(stored.payloadBytes,Buffer.byteLength(encryptedData))
  const ref=JSON.parse(stored.encryptedData.slice(7))
  assert.equal(ref.bytes,Buffer.byteLength(encryptedData))
  const bucket=await h.mf.getR2Bucket('serotine_files')
  assert.equal(await (await bucket.get(ref.key)).text(),encryptedData)
  const feed=await h.request(b,'event:sync')
  assert.equal(await h.client.decryptFromPeer(feed.messages[0].encryptedData,b.pair.privateKey,a.publicKey),plaintext)
  assert.deepEqual(await h.request({...b,sessionId:crypto.randomUUID()},'event:sync'),feed)
  assert.equal((await h.request(outsider,'event:sync')).messages.length,0)
  await h.metrics()
  await h.request(a,'event:send',{...data,encryptedData:'changed packet'.repeat(20)})
  assert.equal((await h.metrics()).rowsWritten,0,'idempotent retry has no D1 mutation')
  assert.deepEqual(await h.request(b,'event:sync'),feed)
  await bucket.delete(ref.key)
  const failed=await (await h.request(b,'event:sync',{}, {raw:true})).json()
  assert.equal(failed.success,false)
  assert.equal(failed.nextCursor,undefined)
  assert.equal(await d1.prepare('SELECT COUNT(*) AS n FROM RelayEvent').first('n'),1)
  await bucket.put(ref.key,encryptedData)
  assert.deepEqual(await h.request(b,'event:sync'),feed)
})

test('replay guards survive DO restart and scope nonces across HTTP and socket authentication', async t=>{
  const h=await harness(root,true);t.after(()=>h.dispose())
  const a=await h.identity(),data={sessionId:a.sessionId}
  const proof=await h.client.createRequestProof('call:socket',data,a.privateKey,a.publicKey,h.now())
  await h.request(a,'call:socket',{}, {proof})
  await h.restart()
  await h.tick(60_000) // proofs are valid at the inclusive window boundary
  const duplicate=await h.request(a,'call:socket',{}, {proof,raw:true})
  assert.equal(duplicate.status,409)
  const d1=await h.mf.getD1Database('serotine_db')
  assert.equal(await d1.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE name='RequestNonce'").first('n'),0)
  const result=await realtime(h,'SELECT COUNT(*) AS n FROM RequestNonce')
  assert.equal(result.results[0].n,1)
})

test('concurrent linked-device claims stay atomic and permanent retirement ends the selected call', async t=>{
  const h=await harness(root,true);t.after(()=>h.dispose())
  const a=await h.identity(),b=await h.identity(),linked={...b,sessionId:crypto.randomUUID()}
  for(const p of [a,b,linked])await h.request(p,'call:heartbeat',{peers:[p===a?b.publicKey:a.publicKey],incomingPeers:[p===a?b.publicKey:a.publicKey]})
  const callId=crypto.randomUUID()
  await h.request(a,'call:invite',{noHistory:false,signal:{id:crypto.randomUUID(),callId,sender:a.publicKey,recipient:b.publicKey,senderSession:a.sessionId,targetSession:null,expiresAt:h.now()+30_000,encryptedData:'e'.repeat(80)}})
  const claims=await Promise.all([b,linked].map(p=>h.request(p,'call:claim',{callId,noHistory:false},{raw:true})))
  assert.deepEqual(claims.map(r=>r.status).sort(),[200,409])
  await h.request(b,'identity:retire')
  const snapshot=await h.request(a,'call:poll',{after:0})
  assert.equal(snapshot.sessions[0].status,'ended')
  assert.equal((await h.request(linked,'call:poll',{after:0},{raw:true})).status,403)
  assert.equal((await h.request(a,'call:capability',{peer:b.publicKey})).available,false)
})

test('R2 conditional chunk publication prevents conflicting overwrite and writes compact metadata once', async t=>{
  const h=await harness(root,true);t.after(()=>h.dispose())
  const a=await h.identity(),b=await h.identity(),uploadId=crypto.randomUUID()
  const capability='a'.repeat(64)
  await h.request(a,'file:init',{uploadId,size:3,chunkCount:1,accessHash:await digest(new TextEncoder().encode(capability))})
  const bytes=new Uint8Array(19),different=new Uint8Array(19).fill(1)
  const data=async bytes=>({uploadId,index:0,size:19,digest:await digest(bytes)})
  await h.metrics()
  const writes=await Promise.all([bytes,different].map(async bytes=>h.request(a,'file:chunk',await data(bytes),{bytes,raw:true})))
  assert.deepEqual(writes.map(r=>r.status).sort(),[200,409])
  const d1=await h.mf.getD1Database('serotine_db'),row=await d1.prepare('SELECT * FROM FileUploadChunk').first()
  const counts=await h.metrics()
  assert.equal(counts.rowsWritten,2,'one row plus its primary-key index')
  assert.equal(row.ready,1)
  await h.request(a,'file:complete',{uploadId});await h.request(a,'file:publish',{uploadId})
  const response=await h.request(b,'file:read',{uploadId,index:0,capability},{raw:true})
  assert.equal(response.status,200)
  assert.equal(await digest(await response.arrayBuffer()),row.digest)
  await h.metrics()
  const winner=await digest(bytes)===row.digest?bytes:different
  await h.request(a,'file:chunk',await data(winner),{bytes:winner})
  await h.request(a,'file:complete',{uploadId});await h.request(a,'file:publish',{uploadId})
  assert.equal((await h.metrics()).rowsWritten,0,'completed upload retries never rewrite D1')
})

test('cutover imports active calls, nonce replay guards, signal cursors and permanent room checkpoints', async t=>{
  const h=await harness(root,true);t.after(()=>h.dispose())
  await h.mode('1')
  const a=await h.identity(),b=await h.identity()
  const proof=await h.client.createRequestProof('call:socket',{sessionId:a.sessionId},a.privateKey,a.publicKey,h.now())
  await h.request(a,'call:socket',{}, {proof})
  for(const p of [a,b])await h.request(p,'call:heartbeat',{peers:[p===a?b.publicKey:a.publicKey],incomingPeers:[p===a?b.publicKey:a.publicKey]})
  const group={id:`group:${crypto.randomUUID()}`,name:'Migration',admin:a.publicKey,members:[a.publicKey,b.publicKey],epoch:2,updatedAt:h.now()}
  const target={kind:'group',group:await h.client.signGroup(group,a)}
  await h.request(a,'room:status',{target})
  const callId=crypto.randomUUID()
  await h.request(a,'call:invite',{noHistory:false,signal:{id:crypto.randomUUID(),callId,sender:a.publicKey,recipient:b.publicKey,senderSession:a.sessionId,targetSession:null,expiresAt:h.now()+30_000,encryptedData:'i'.repeat(80)}})
  await h.request(b,'call:claim',{callId,noHistory:false})
  await h.request(b,'call:send',{noHistory:false,signal:{id:crypto.randomUUID(),callId,sender:b.publicKey,recipient:a.publicKey,senderSession:b.sessionId,targetSession:a.sessionId,expiresAt:h.now()+30_000,encryptedData:'a'.repeat(80)}})
  const before=await h.request(a,'call:poll',{after:0})
  const d1=await h.mf.getD1Database('serotine_db')
  const priorNonceCount=await d1.prepare('SELECT COUNT(*) AS n FROM RequestNonce').first('n')
  await h.mode('2')
  const after=await h.request(a,'call:poll',{after:0})
  assert.deepEqual(after,before)
  await assert.rejects(d1.prepare('UPDATE CallSession SET recipientSession = ? WHERE callId = ?').bind(crypto.randomUUID(),callId).run(),/Realtime storage moved/)
  await assert.rejects(d1.prepare('DELETE FROM RequestNonce').run(),/Realtime storage moved/)
  assert.equal((await h.request(a,'call:socket',{}, {proof,raw:true})).status,409)
  const stale={kind:'group',group:await h.client.signGroup({...group,epoch:1},a)}
  assert.equal((await h.request(a,'room:status',{target:stale},{raw:true})).status,409)
  assert.equal(await d1.prepare('SELECT COUNT(*) AS n FROM RequestNonce').first('n'),priorNonceCount)
  await h.restart()
  assert.equal((await h.request(a,'room:status',{target:stale},{raw:true})).status,409)
  assert.equal((await h.request(a,'call:poll',{after:0})).sessions[0].status,'active')
})
