const assert = require('node:assert/strict')
const path = require('node:path')
const { test } = require('node:test')
const { harness } = require('./support/d1-workload.cjs')
const root = path.resolve(__dirname, '..')
const digest = async bytes => Buffer.from(await crypto.subtle.digest('SHA-256', bytes)).toString('hex')
const direct = (a, b, timestamp) => { const [first, second] = [a.publicKey, b.publicKey].sort(); return { kind: 'direct', first, second, timestamp } }
const objects = async bucket => (await bucket.list()).objects

test('production storage v2 persists scoped terminal authority and routed proof replays across DO restart', { timeout: 90_000 }, async t => {
  const h = await harness(root, true); t.after(() => h.dispose())
  const a = await h.identity(), b = await h.identity(), stranger = await h.identity(), scope = direct(a, b, h.now())
  const packet = { id: crypto.randomUUID(), recipientPubKey: b.publicKey, encryptedData: 'encrypted packet'.repeat(4), retention: scope }
  await h.request(a, 'event:send', packet)
  const bucket = await h.mf.getR2Bucket('serotine_files'), d1 = await h.mf.getD1Database('serotine_db')
  assert.equal((await objects(bucket)).length, 1)
  assert.match((await objects(bucket))[0].key, /relay-payloads\/scoped-v1\//)
  assert.equal((await h.request(stranger, 'retention:close', { scope }, { raw: true })).status, 403)
  const proof = await h.client.createRequestProof('retention:close', { scope }, b.privateKey, b.publicKey, h.now())
  const closed = await h.request(b, 'retention:close', { scope }, { proof })
  assert.equal(closed.removed, 1)
  assert.equal((await objects(bucket)).length, 0)
  assert.equal(await d1.prepare('SELECT COUNT(*) AS n FROM RelayEvent').first('n'), 0)
  assert.equal(await d1.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE name='RequestNonce'").first('n'), 0, 'replay state remains in the realtime DO')
  await h.restart()
  assert.equal((await h.request(b, 'retention:close', { scope }, { proof, raw: true })).status, 409)
  const stale = await (await h.request(a, 'event:send', { ...packet, id: crypto.randomUUID() }, { raw: true })).json()
  assert.equal(stale.success, false)
  assert.deepEqual((await h.request(b, 'event:sync')).messages, [])
})

test('real R2 attachment completion reclaims bytes with one delete batch; duplicate acknowledgements cost zero D1 writes and zero R2 operations', { timeout: 90_000 }, async t => {
  const h = await harness(root, true); t.after(() => h.dispose())
  const a = await h.identity(), b = await h.identity(), uploadId = crypto.randomUUID(), messageId = crypto.randomUUID(), size = 32 * 1024
  const capability = 'b'.repeat(64), bytes = new Uint8Array(size + 16).fill(7)
  await h.request(a, 'file:init', { uploadId, size, chunkCount: 1, accessHash: await digest(new TextEncoder().encode(capability)) })
  const chunkHash = await digest(bytes)
  await h.request(a, 'file:chunk', { uploadId, index: 0, size: bytes.byteLength, digest: chunkHash }, { bytes })
  await h.request(a, 'file:complete', { uploadId }); await h.request(a, 'file:publish', { uploadId })
  const manifestHash = await digest(new TextEncoder().encode(JSON.stringify([chunkHash])))
  await h.request(a, 'file:delivery', { uploadId, messageId, manifestHash, recipients: [b.publicKey], scope: direct(a, b, h.now()) })
  const bucket = await h.mf.getR2Bucket('serotine_files'), d1 = await h.mf.getD1Database('serotine_db')
  assert.equal((await objects(bucket)).reduce((sum, value) => sum + value.size, 0), size + 16)
  const response = await h.request(b, 'file:read', { uploadId, index: 0, capability }, { raw: true })
  assert.equal(await digest(await response.arrayBuffer()), chunkHash)
  await h.metrics(); await h.mf.dispatchFetch('https://serotine.example/__filemetrics')
  await h.tick(10_000)
  const completion = { uploadId, messageId, manifestHash, capability }
  await h.request(b, 'file:received', completion)
  assert.equal((await objects(bucket)).length, 0)
  assert.equal(await d1.prepare('SELECT COUNT(*) AS n FROM FileDelivery').first('n'), 0)
  assert.equal(await d1.prepare('SELECT COUNT(*) AS n FROM FileUploadChunk').first('n'), 0)
  const first = await h.metrics(), r2 = await (await h.mf.dispatchFetch('https://serotine.example/__filemetrics')).json()
  assert.ok(first.rowsWritten > 0 && first.rowsWritten < 40, JSON.stringify(first))
  assert.deepEqual(r2, { puts: 0, gets: 0, deletes: 1, deletedKeys: 1 })
  await h.request(b, 'file:received', completion)
  assert.equal((await h.metrics()).rowsWritten, 0)
  assert.deepEqual(await (await h.mf.dispatchFetch('https://serotine.example/__filemetrics')).json(), { puts: 0, gets: 0, deletes: 0, deletedKeys: 0 })
  t.diagnostic(`32,784 R2 bytes reclaimed after 10 seconds; ${first.rowsWritten} actual D1 rows written including indexes; one R2 delete batch. Duplicate: 0 D1 writes, 0 R2 operations.`)
})
