import Link from "next/link"
import { ArrowUpRight, Shield, KeyRound, Lock, MessageSquare } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function LandingPage() {
  return <div className="min-h-dvh">
    <header className="mx-auto flex h-24 max-w-6xl items-center justify-between border-b border-border px-6"><Link href="/" className="flex items-center gap-3"><Shield className="size-6 text-primary" /><span className="font-semibold tracking-tight text-2xl">Serotine</span></Link><Link href="/login"><Button variant="outline">Open messages <ArrowUpRight className="ml-2 size-4" /></Button></Link></header>
    <main className="mx-auto max-w-6xl px-6">
      <section className="grid items-center gap-14 py-16 md:grid-cols-[1.3fr_1fr] md:gap-20 md:py-28">
        <div><p className="mb-6 text-xs font-medium uppercase tracking-[0.2em] text-primary">A private place to talk</p><h1 className="max-w-2xl text-5xl leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">For conversations<br /><span className="text-muted-foreground">that are yours.</span></h1><p className="mt-7 max-w-lg text-lg leading-relaxed text-muted-foreground">Encrypted messaging with an identity you create on your own device. No phone number. No email address.</p><div className="mt-9 flex flex-wrap items-center gap-5"><Link href="/login"><Button size="lg" className="h-12 px-6">Start a conversation <ArrowUpRight className="ml-2 size-4" /></Button></Link><a href="#how-it-works" className="text-sm text-muted-foreground underline-offset-4 hover:text-foreground hover:underline">How it works</a></div></div>
        <div className="rounded-2xl border border-border bg-card p-7 shadow-sm sm:p-8"><div className="mb-8 flex items-center gap-3 border-b border-border pb-6"><Lock className="size-5 text-primary" /><h2 className="font-sans text-base font-medium">Private by design. Clear about limits.</h2></div><ol className="space-y-7">{[["01", "Create your identity", "Your browser generates a private key and a public contact address."], ["02", "Exchange addresses", "Share your public address with someone you trust and add theirs."], ["03", "Make room for a conversation", "Messages are encrypted before sending and saved in your browser."]].map(([number, title, text]) => <li key={number} className="flex gap-4"><span className="pt-1 font-mono text-xs text-muted-foreground">{number}</span><div><h3 className="font-sans text-base text-foreground">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div></li>)}</ol></div>
      </section>
      <section id="how-it-works" className="grid gap-8 border-t border-border py-12 md:grid-cols-3 md:py-16">
        {[{ icon: KeyRound, title: "An identity you keep", text: "Private keys stay in your browser. Download an encrypted backup so you can recover your identity on another device." }, { icon: Lock, title: "Encrypted from the start", text: "Messages and connection signals are encrypted. Verify contact addresses separately; protecting your device and browser still matters." }, { icon: MessageSquare, title: "Delivery that can wait", text: "The relay keeps encrypted messages for seven days so your linked devices can catch up. Save a full backup to preserve older conversations." }].map(item => <div key={item.title}><item.icon className="mb-5 size-5 text-primary/80" /><h2 className="mb-3 text-xl">{item.title}</h2><p className="text-base leading-relaxed text-muted-foreground">{item.text}</p></div>)}
      </section>
    </main>
    <footer className="mx-auto flex max-w-6xl flex-col gap-3 border-t border-border px-6 py-7 text-xs leading-relaxed text-muted-foreground sm:flex-row sm:justify-between"><span>Serotine · Private conversations</span><p className="max-w-xl">The relay can see routing addresses and timing. Browser history does not automatically disappear. This software has not undergone an independent security audit.</p></footer>
  </div>
}
