-- Enable necessary extensions
create extension if not exists "pgcrypto";

-- Create profiles table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS) for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Create devices table for vouching system
create table if not exists public.devices (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  device_name text not null,
  device_id text not null, -- Unique identifier generated by client
  public_key text not null,
  last_seen timestamp with time zone default now(),
  is_trusted boolean default false,
  created_at timestamp with time zone default now(),
  
  unique(user_id, device_id)
);

-- Set up RLS for devices
alter table public.devices enable row level security;

create policy "Users can view their own devices."
  on public.devices for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own devices."
  on public.devices for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own devices."
  on public.devices for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own devices."
  on public.devices for delete
  using ( auth.uid() = user_id );

-- Function to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on signup
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
